version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/dairy-backend:latest
    container_name: dairy-backend
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    network_mode: "host"

  ui:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/dairy-ui:latest
    container_name: dairy-ui
    restart: always
    network_mode: "host"

